# Generated by Django 5.0.3 on 2024-03-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="assignements",
            field=models.ManyToManyField(related_name="students", to="lms.assignment"),
        ),
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="lms.class"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lms.class"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
