# Generated by Django 5.0.3 on 2024-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_date_joined_customuser_groups_and_more"),
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="assignements",
            field=models.ManyToManyField(related_name="teachers", to="lms.assignment"),
        ),
    ]
